#!/usr/bin/env bash
set -euo pipefail

# =========================
# User Config (edit here)
# =========================
# Tip: you can also override any of these via env vars when launching the script.

# Core paths
MINI_SRC="${MINI_SRC:-/Users/evanwu/Desktop/autoguiworld/mini-swe-agent/src}"
FSM_PATH="${FSM_PATH:-trajectory/fsm/generator/fsm_perfect_outputs/blog_platform-medium/perfect_fsm_blog_platform-medium_100.json}"
# Base output root; final theme dir is auto-derived as <base>/<theme>-web/<timestamp>.
PROJECT_DIR="${PROJECT_DIR:-autowebworld/web_outputs}"
CONTEXT_ROOT="${CONTEXT_ROOT:-autowebworld/react_context}"
TEMPLATE_DIR="${TEMPLATE_DIR:-autowebworld/template/react_template}"
PRELOADED_SKILL_FILE="${PRELOADED_SKILL_FILE:-/Users/evanwu/.codex/skills/frontend-design-ultimate/SKILL.md}"

# OpenAI endpoint/auth
OPENAI_BASE_URL="${OPENAI_BASE_URL:-https://newapi.deepwisdom.ai/v1}"
OPENAI_API_KEY="${OPENAI_API_KEY:-}"

# Model/runtime config
MODEL="${MODEL:-gemini-3.1-pro-preview}"
MODEL_PROVIDER="${MODEL_PROVIDER:-openai}"
MAX_TURNS="${MAX_TURNS:-50}"
NPM_CLIENT="${NPM_CLIENT:-npm}"
SKIP_INIT="${SKIP_INIT:-0}"   # 1 => pass --skip-init
RUN_ID="${RUN_ID:-}"          # optional; empty => auto generated by python

# =========================
# Internal (normally no edit)
# =========================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

# Resolve relative config paths against repo root for predictable behavior.
[[ "${FSM_PATH}" = /* ]] || FSM_PATH="${REPO_DIR}/${FSM_PATH}"
[[ "${PROJECT_DIR}" = /* ]] || PROJECT_DIR="${REPO_DIR}/${PROJECT_DIR}"
[[ "${CONTEXT_ROOT}" = /* ]] || CONTEXT_ROOT="${REPO_DIR}/${CONTEXT_ROOT}"
[[ "${TEMPLATE_DIR}" = /* ]] || TEMPLATE_DIR="${REPO_DIR}/${TEMPLATE_DIR}"
[[ "${PRELOADED_SKILL_FILE}" = /* ]] || PRELOADED_SKILL_FILE="${REPO_DIR}/${PRELOADED_SKILL_FILE}"

export OPENAI_BASE_URL
export OPENAI_API_KEY

if [[ "${1:-}" == "-h" || "${1:-}" == "--help" ]]; then
  exec python "${REPO_DIR}/autowebworld/react_coding_agent.py" --help
fi

if [[ -z "${OPENAI_API_KEY:-}" ]]; then
  echo "OPENAI_API_KEY is not set."
  echo "Please run: export OPENAI_API_KEY=YOUR_KEY"
  exit 1
fi

cmd=(
  python "${REPO_DIR}/autowebworld/react_coding_agent.py"
  --mini-src "${MINI_SRC}"
  --fsm "${FSM_PATH}"
  --project-dir "${PROJECT_DIR}"
  --context-root "${CONTEXT_ROOT}"
  --template-dir "${TEMPLATE_DIR}"
  --preloaded-skill-file "${PRELOADED_SKILL_FILE}"
  --model "${MODEL}"
  --model-provider "${MODEL_PROVIDER}"
  --max-turns "${MAX_TURNS}"
  --npm-client "${NPM_CLIENT}"
)

if [[ -n "${RUN_ID}" ]]; then
  cmd+=(--run-id "${RUN_ID}")
fi

if [[ "${SKIP_INIT}" == "1" ]]; then
  cmd+=(--skip-init)
fi

if [[ $# -gt 0 ]]; then
  cmd+=("$@")
fi

echo "Running:"
printf ' %q' "${cmd[@]}"
echo

exec "${cmd[@]}"
