import os

API_KEY = os.getenv("OPENAI_API_KEY", "")
BASE_URL = os.getenv("OPENAI_BASE_URL", "")
MODEL = "gemini-2.5-flash"
TEMPERATURE = 0.7
MAX_TOKENS = 32768

IMAGE_RESIZE_WIDTH = 512
IMAGE_RESIZE_HEIGHT = 512
IMAGE_QUALITY = 90

