import { defineStore } from 'pinia';

export const useDataStore = defineStore('data', {
  state: () => ({
    currentUser: {
      id: 'user_current',
      name: 'Alex Morgan',
      avatar: '/images/UserAvatar.jpg',
      status: 'Available'
    },
    users: [
      { id: 'user_1', name: 'Sarah Connor', avatar: '/images/UserAvatar.jpg', status: 'Busy' },
      { id: 'user_2', name: 'John Doe', avatar: '/images/User.jpg', status: 'Offline' },
      { id: 'user_3', name: 'Jane Smith', avatar: '/images/JaneSmith.jpg', status: 'Available' },
      { id: 'user_4', name: 'Mike Ross', avatar: '/images/Meeting.jpg', status: 'In a meeting' },
      { id: 'user_5', name: 'Rachel Zane', avatar: '/images/RachelZane.jpg', status: 'Available' },
      { id: 'user_6', name: 'Harvey Specter', avatar: '/images/HarveySpecter.jpg', status: 'Do not disturb' },
      { id: 'user_7', name: 'Donna Paulsen', avatar: '/images/DonnaPaulsen.jpg', status: 'Available' },
      { id: 'user_8', name: 'Louis Litt', avatar: '/images/LouisLitt.jpg', status: 'Offline' },
      { id: 'user_9', name: 'Jessica Pearson', avatar: '/images/JessicaPearson.jpg', status: 'Busy' },
      { id: 'user_10', name: 'Katrina Bennett', avatar: '/images/Avatar.jpg', status: 'Available' },
      { id: 'user_11', name: 'Robert Zane', avatar: '/images/RobertZane.jpg', status: 'Away' },
      { id: 'user_12', name: 'Samantha Wheeler', avatar: '/images/User.jpg', status: 'Available' },
      { id: 'user_13', name: 'Alex Williams', avatar: '/images/User.jpg', status: 'In a call' },
      { id: 'user_14', name: 'Brian Altman', avatar: '/images/Brian.jpg', status: 'Offline' },
      { id: 'user_15', name: 'Gretchen Bodinski', avatar: '/images/Gretchen.jpg', status: 'Available' }
    ],
    teams: [
      { id: 'team_1', name: 'Engineering', description: 'Engineering department general team', activity: 90, isFavorite: true, image: '/images/Team.jpg' },
      { id: 'team_2', name: 'Marketing', description: 'Marketing campaigns and assets', activity: 75, isFavorite: false, image: '/images/Marketing.jpg' },
      { id: 'team_3', name: 'Sales', description: 'Sales leads and pipeline', activity: 85, isFavorite: true, image: '/images/Sales.jpg' },
      { id: 'team_4', name: 'Product Management', description: 'Product roadmap and planning', activity: 60, isFavorite: false, image: '/images/ProductManagement.jpg' },
      { id: 'team_5', name: 'Human Resources', description: 'HR policies and recruitment', activity: 40, isFavorite: false, image: '/images/HumanResources.jpg' },
      { id: 'team_6', name: 'Finance', description: 'Financial planning and analysis', activity: 50, isFavorite: false, image: '/images/Finance.jpg' },
      { id: 'team_7', name: 'Design', description: 'UX/UI Design team', activity: 80, isFavorite: true, image: '/images/Design.jpg' },
      { id: 'team_8', name: 'Operations', description: 'Company operations', activity: 55, isFavorite: false, image: '/images/Operations.jpg' },
      { id: 'team_9', name: 'Legal', description: 'Legal counsel and contracts', activity: 30, isFavorite: false, image: '/images/Legal.jpg' },
      { id: 'team_10', name: 'Customer Support', description: 'Support tickets and feedback', activity: 95, isFavorite: true, image: '/images/CustomerSupport.jpg' },
      { id: 'team_11', name: 'IT Support', description: 'Internal IT support', activity: 65, isFavorite: false, image: '/images/ITSupport.jpg' },
      { id: 'team_12', name: 'Executive', description: 'Executive leadership team', activity: 45, isFavorite: false, image: '/images/Executive.jpg' },
      { id: 'team_13', name: 'Events', description: 'Company events planning', activity: 70, isFavorite: false, image: '/images/Events.jpg' },
      { id: 'team_14', name: 'Research', description: 'R&D projects', activity: 35, isFavorite: false, image: '/images/Research.jpg' },
      { id: 'team_15', name: 'Social Committee', description: 'Fun and social activities', activity: 88, isFavorite: true, image: '/images/SocialCommittee.jpg' }
    ],
    channels: [
      { id: 'chan_1_1', teamId: 'team_1', name: 'General', type: 'public', unread: 5, activity: 90 },
      { id: 'chan_1_2', teamId: 'team_1', name: 'Frontend', type: 'public', unread: 2, activity: 85 },
      { id: 'chan_1_3', teamId: 'team_1', name: 'Backend', type: 'public', unread: 0, activity: 70 },
      { id: 'chan_1_4', teamId: 'team_1', name: 'DevOps', type: 'private', unread: 1, activity: 60 },
      { id: 'chan_2_1', teamId: 'team_2', name: 'General', type: 'public', unread: 10, activity: 80 },
      { id: 'chan_2_2', teamId: 'team_2', name: 'Social Media', type: 'public', unread: 0, activity: 50 },
      { id: 'chan_2_3', teamId: 'team_2', name: 'Campaigns', type: 'private', unread: 3, activity: 75 },
      { id: 'chan_3_1', teamId: 'team_3', name: 'General', type: 'public', unread: 0, activity: 40 },
      { id: 'chan_3_2', teamId: 'team_3', name: 'Leads', type: 'public', unread: 8, activity: 95 },
      { id: 'chan_7_1', teamId: 'team_7', name: 'General', type: 'public', unread: 2, activity: 60 },
      { id: 'chan_7_2', teamId: 'team_7', name: 'Design System', type: 'public', unread: 0, activity: 45 },
      { id: 'chan_7_3', teamId: 'team_7', name: 'Critiques', type: 'private', unread: 4, activity: 70 },
      { id: 'chan_10_1', teamId: 'team_10', name: 'General', type: 'public', unread: 15, activity: 98 },
      { id: 'chan_10_2', teamId: 'team_10', name: 'Urgent', type: 'public', unread: 5, activity: 90 },
      { id: 'chan_15_1', teamId: 'team_15', name: 'General', type: 'public', unread: 0, activity: 50 },
      { id: 'chan_15_2', teamId: 'team_15', name: 'Party Planning', type: 'public', unread: 1, activity: 65 }
    ],
    chats: [
      { id: 'chat_1', userId: 'user_1', name: 'Sarah Connor', lastMessage: 'See you tomorrow!', time: '10:30 AM', unread: 1, activity: 80, image: '/images/UserAvatar.jpg' },
      { id: 'chat_2', userId: 'user_2', name: 'John Doe', lastMessage: 'Can you review this?', time: '09:15 AM', unread: 0, activity: 40, image: '/images/User.jpg' },
      { id: 'chat_3', userId: 'user_3', name: 'Jane Smith', lastMessage: 'Meeting canceled', time: 'Yesterday', unread: 0, activity: 20, image: '/images/JaneSmith.jpg' },
      { id: 'chat_4', userId: 'user_4', name: 'Mike Ross', lastMessage: 'Thanks for the help', time: 'Yesterday', unread: 0, activity: 30, image: '/images/Meeting.jpg' },
      { id: 'chat_5', userId: 'user_5', name: 'Rachel Zane', lastMessage: 'Lunch?', time: 'Yesterday', unread: 2, activity: 70, image: '/images/RachelZane.jpg' },
      { id: 'chat_6', userId: 'user_6', name: 'Harvey Specter', lastMessage: 'Get it done.', time: 'Mon', unread: 5, activity: 90, image: '/images/HarveySpecter.jpg' },
      { id: 'chat_7', userId: 'user_7', name: 'Donna Paulsen', lastMessage: 'I know.', time: 'Mon', unread: 0, activity: 60, image: '/images/DonnaPaulsen.jpg' },
      { id: 'chat_8', userId: 'user_8', name: 'Louis Litt', lastMessage: 'This is unacceptable!', time: 'Sun', unread: 1, activity: 85, image: '/images/LouisLitt.jpg' },
      { id: 'chat_9', userId: 'user_9', name: 'Jessica Pearson', lastMessage: 'My office. Now.', time: 'Sat', unread: 0, activity: 50, image: '/images/JessicaPearson.jpg' },
      { id: 'chat_10', userId: 'user_10', name: 'Katrina Bennett', lastMessage: 'Draft looks good', time: 'Fri', unread: 0, activity: 35, image: '/images/Avatar.jpg' },
      { id: 'chat_11', userId: 'user_11', name: 'Robert Zane', lastMessage: 'Golf this weekend?', time: 'Thu', unread: 0, activity: 10, image: '/images/RobertZane.jpg' },
      { id: 'chat_12', userId: 'user_12', name: 'Samantha Wheeler', lastMessage: 'Lets go boxing', time: 'Wed', unread: 0, activity: 25, image: '/images/User.jpg' },
      { id: 'chat_13', userId: 'user_13', name: 'Alex Williams', lastMessage: 'Family dinner', time: 'Tue', unread: 0, activity: 15, image: '/images/User.jpg' },
      { id: 'chat_14', userId: 'user_14', name: 'Brian Altman', lastMessage: 'Baby photos attached', time: 'Mon', unread: 0, activity: 5, image: '/images/Brian.jpg' },
      { id: 'chat_15', userId: 'user_15', name: 'Gretchen Bodinski', lastMessage: 'Already handled it', time: 'Mon', unread: 0, activity: 45, image: '/images/Gretchen.jpg' }
    ],
    messages: [
      { id: 'msg_1', chatId: 'chat_1', text: 'Hey, are we still on for the meeting?', sender: 'me', time: '10:00 AM' },
      { id: 'msg_2', chatId: 'chat_1', text: 'Yes, absolutely.', sender: 'them', time: '10:05 AM' },
      { id: 'msg_3', chatId: 'chat_1', text: 'Great, see you then.', sender: 'me', time: '10:06 AM' },
      { id: 'msg_4', chatId: 'chat_1', text: 'See you tomorrow!', sender: 'them', time: '10:30 AM' },
      { id: 'msg_5', chatId: 'chat_6', text: 'The documents are ready.', sender: 'me', time: '09:00 AM' },
      { id: 'msg_6', chatId: 'chat_6', text: 'Bring them to me.', sender: 'them', time: '09:05 AM' },
      { id: 'msg_7', chatId: 'chat_6', text: 'On my way.', sender: 'me', time: '09:06 AM' },
      { id: 'msg_8', chatId: 'chat_6', text: 'Get it done.', sender: 'them', time: '09:10 AM' }
    ],
    calendarEvents: [
      { id: 'evt_1', title: 'Daily Standup', start_time: '2025-12-10 09:00', end_time: '2025-12-10 09:15', type: 'meeting', organizer: 'user_1' },
      { id: 'evt_2', title: 'Project Review', start_time: '2025-12-10 14:00', end_time: '2025-12-10 15:00', type: 'meeting', organizer: 'user_2' },
      { id: 'evt_3', title: 'Client Call', start_time: '2025-12-11 10:00', end_time: '2025-12-11 11:00', type: 'meeting', organizer: 'me' },
      { id: 'evt_4', title: 'Lunch with Team', start_time: '2025-12-11 12:00', end_time: '2025-12-11 13:00', type: 'social', organizer: 'user_5' },
      { id: 'evt_5', title: 'Design Sync', start_time: '2025-12-12 11:00', end_time: '2025-12-12 12:00', type: 'meeting', organizer: 'user_7' },
      { id: 'evt_6', title: 'Town Hall', start_time: '2025-12-12 16:00', end_time: '2025-12-12 17:00', type: 'company', organizer: 'user_12' },
      { id: 'evt_7', title: 'Sprint Planning', start_time: '2025-12-15 10:00', end_time: '2025-12-15 12:00', type: 'meeting', organizer: 'user_1' },
      { id: 'evt_8', title: '1:1 with Manager', start_time: '2025-12-16 14:00', end_time: '2025-12-16 14:30', type: 'meeting', organizer: 'user_9' },
      { id: 'evt_9', title: 'Marketing Sync', start_time: '2025-12-16 15:00', end_time: '2025-12-16 16:00', type: 'meeting', organizer: 'user_2' },
      { id: 'evt_10', title: 'Dentist Appointment', start_time: '2025-12-17 08:00', end_time: '2025-12-17 09:00', type: 'personal', organizer: 'me' },
      { id: 'evt_11', title: 'Code Review', start_time: '2025-12-17 13:00', end_time: '2025-12-17 14:00', type: 'work', organizer: 'user_4' },
      { id: 'evt_12', title: 'Product Launch', start_time: '2025-12-18 09:00', end_time: '2025-12-18 10:00', type: 'company', organizer: 'user_12' },
      { id: 'evt_13', title: 'Happy Hour', start_time: '2025-12-19 17:00', end_time: '2025-12-19 19:00', type: 'social', organizer: 'user_15' },
      { id: 'evt_14', title: 'Board Meeting', start_time: '2025-12-20 10:00', end_time: '2025-12-20 12:00', type: 'company', organizer: 'user_9' },
      { id: 'evt_15', title: 'Team Building', start_time: '2025-12-22 09:00', end_time: '2025-12-22 17:00', type: 'company', organizer: 'user_5' }
    ],
    calls: [
      { id: 'call_1', userId: 'user_1', name: 'Sarah Connor', type: 'incoming', duration: 120, time: 'Today, 10:00 AM', status: 'missed', image: '/images/UserAvatar.jpg' },
      { id: 'call_2', userId: 'user_2', name: 'John Doe', type: 'outgoing', duration: 300, time: 'Today, 09:00 AM', status: 'completed', image: '/images/User.jpg' },
      { id: 'call_3', userId: 'user_3', name: 'Jane Smith', type: 'incoming', duration: 60, time: 'Yesterday', status: 'completed', image: '/images/JaneSmith.jpg' },
      { id: 'call_4', userId: 'user_4', name: 'Mike Ross', type: 'missed', duration: 0, time: 'Yesterday', status: 'missed', image: '/images/Meeting.jpg' },
      { id: 'call_5', userId: 'user_6', name: 'Harvey Specter', type: 'outgoing', duration: 900, time: 'Mon', status: 'completed', image: '/images/HarveySpecter.jpg' },
      { id: 'call_6', userId: 'user_7', name: 'Donna Paulsen', type: 'incoming', duration: 180, time: 'Mon', status: 'completed', image: '/images/DonnaPaulsen.jpg' },
      { id: 'call_7', userId: 'user_8', name: 'Louis Litt', type: 'missed', duration: 0, time: 'Sun', status: 'missed', image: '/images/LouisLitt.jpg' },
      { id: 'call_8', userId: 'user_1', name: 'Sarah Connor', type: 'outgoing', duration: 45, time: 'Sat', status: 'completed', image: '/images/UserAvatar.jpg' },
      { id: 'call_9', userId: 'user_9', name: 'Jessica Pearson', type: 'incoming', duration: 600, time: 'Fri', status: 'completed', image: '/images/JessicaPearson.jpg' },
      { id: 'call_10', userId: 'user_10', name: 'Katrina Bennett', type: 'outgoing', duration: 120, time: 'Fri', status: 'completed', image: '/images/Avatar.jpg' },
      { id: 'call_11', userId: 'user_11', name: 'Robert Zane', type: 'missed', duration: 0, time: 'Thu', status: 'missed', image: '/images/RobertZane.jpg' },
      { id: 'call_12', userId: 'user_13', name: 'Alex Williams', type: 'incoming', duration: 240, time: 'Wed', status: 'completed', image: '/images/User.jpg' },
      { id: 'call_13', userId: 'user_14', name: 'Brian Altman', type: 'outgoing', duration: 60, time: 'Wed', status: 'completed', image: '/images/Brian.jpg' },
      { id: 'call_14', userId: 'user_15', name: 'Gretchen Bodinski', type: 'incoming', duration: 30, time: 'Tue', status: 'completed', image: '/images/Gretchen.jpg' },
      { id: 'call_15', userId: 'user_2', name: 'John Doe', type: 'missed', duration: 0, time: 'Tue', status: 'missed', image: '/images/User.jpg' }
    ]
  }),
  persist: {
    storage: sessionStorage,
  },
});